### ISSUE TITLE
GetFixtureList().Next() Never returns falsey

### ISSUE THREAD

**Issue by mfs409** [Birch-san/box2d-wasm#11]
I am trying to port from a different TypeScript Box2D port, but I am finding that all code of this form has infinite loops:

```
// Set all fixtures to be sensors
for (let f = this.body.GetFixtureList(); f; f = f.GetNext()) {
    f.SetSensor(!true);
}
```
It seems that `f.GetNext()` never returns `undefined`, `null`, or `false`, and so the loop keeps running forever.

**Comment by jordandcarter** [comment]
I had the same issue and used this with success. I am iterating over the bodies list though, but it might work out the same.

`for(let body = world.GetBodyList(); box2D.getPointer(body) !== 0; body = body.GetNext()){`

**Comment by mfs409** [comment]
Awesome.  Thanks a ton :)
