### ISSUE TITLE
Working Demo?

### ISSUE THREAD

**Issue by hutzlibu** [Birch-san/box2d-wasm#2]
Hey, I am trying to get your version of Box2D running. 

But I am not clear of the scope of the project and the included Demo does not seem to run out of the box (on a local apache webserver).

Basically, what I want, is to upgrade my old javascript port of box2d (box2dweb) to the more efficient Box2D libary in wasm, but I do not really want to dug deep into the compile chain (or rather touch it not at all at the moment). 

I want to achieve setting up a simple box2d world, which I can manipulate with javascript live in the console. (And then I can port my old work step by step)

So can you clarify, whether I am at the right place, to achieve this with reasonable amount of time? (you seem to focus on ts?) Or should I rather go with https://github.com/kripken/box2d.js ?

**Comment by Birch-san** [comment]
The demo provides its own webserver when run in dev mode (`npm run dev`); I'd recommend using htat.

The demo integrates against the development version of box2d-wasm (i.e. the source in this repository). For this to work, you would need to succeed in building that (which requires setting up an emscripten toolchain).

You can avoid all of this if you change the demo to use the npm distribution of box2d-wasm.

Take a copy of the 'demo' folder (don't copy `node_modules` or `public/build`; let's start from scratch).  
Change this line in your demo/package.json:

https://github.com/Birch-san/box2d-wasm/blob/master/demo/package.json#L33

```diff
- "box2d-wasm": "workspace:*",
+ "box2d-wasm": "1.0.2",
```

Then run in the demo folder:

```bash
npm i
npm run dev
```

And visit http://localhost:5000

I think that should be enough to get the demo working.

**Comment by Birch-san** [comment]
I also expect there's a good chance that `box2d-wasm` should work as a drop-in replacement for (the .wasm distribution of) [box2d.js](https://github.com/kripken/box2d.js). They have a [demo](https://github.com/kripken/box2d.js/blob/master/demo/webgl/box2d.wasm.html#L8) demonstrating how they load it. I've not tried doing this myself, but I use all the same build flags, so I'm optimistic it would work.

**Comment by hutzlibu** [comment]
`npm run dev `
Gives me this error:

```
bundles src/main.ts → public\build\bundle.js...
[!] Error: 'default' is not exported by node_modules\box2d-wasm\build\Box2D.js, imported by src\App.svelte
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src\App.svelte (1:33)
1: <script lang="typescript">
                             ^
2:   import Box2DFactory from 'box2d-wasm';
3:   import type { Box2DEmscriptenModule } from 'box2d-wasm';
Error: 'default' is not exported by node_modules\box2d-wasm\build\Box2D.js, imported by src\App.svelte
    at error (C:\xampp\htdocs\box2d-wasm-master\demo\node_modules\rollup\dist\shared\rollup.js:5252:30)
    at Module.error (C:\xampp\htdocs\box2d-wasm-master\demo\node_modules\rollup\dist\shared\rollup.js:9811:16)
    at handleMissingExport (C:\xampp\htdocs\box2d-wasm-master\demo\node_modules\rollup\dist\shared\rollup.js:9700:28)
    at Module.traceVariable (C:\xampp\htdocs\box2d-wasm-master\demo\node_modules\rollup\dist\shared\rollup.js:10204:24)
    at ModuleScope.findVariable (C:\xampp\htdocs\box2d-wasm-master\demo\node_modules\rollup\dist\shared\rollup.js:8732:39)
    at FunctionScope.findVariable (C:\xampp\htdocs\box2d-wasm-master\demo\node_modules\rollup\dist\shared\rollup.js:2782:38)
    at ChildScope.findVariable (C:\xampp\htdocs\box2d-wasm-master\demo\node_modules\rollup\dist\shared\rollup.js:2782:38)
    at ReturnValueScope.findVariable (C:\xampp\htdocs\box2d-wasm-master\demo\node_modules\rollup\dist\shared\rollup.js:2782:38)
    at ChildScope.findVariable (C:\xampp\htdocs\box2d-wasm-master\demo\node_modules\rollup\dist\shared\rollup.js:2782:38)
    at Identifier$1.bind (C:\xampp\htdocs\box2d-wasm-master\demo\node_modules\rollup\dist\shared\rollup.js:4138:40)
```

**Comment by hutzlibu** [comment]
> I also expect there's a good chance that box2d-wasm should work as a drop-in replacement for (the .wasm distribution of) box2d.js

And yeah, this is what I was hoping for ;)

**Comment by Birch-san** [comment]
> different versions, bindings, ... build tools

@hutzlibu Ah, those are for contributors to develop changes to this repository. You can safely ignore all that.

I've fixed the error you posted above (one-line change in `rollup.config.js`).

I've now written a [simpler demo](https://github.com/Birch-san/box2d-wasm/tree/master/demo/modern). Similar to [box2d.js's WASM demo](https://github.com/kripken/box2d.js/blob/master/demo/webgl/box2d.wasm.html#L8). Tell me if that's any easier to work with.

**Comment by hutzlibu** [comment]
Well, I got the demo to run, like it is, without problems. Thanks.
I see, if I can make it to work, for my use case ...
