### ISSUE TITLE
missing field on b2FixtureDef and b2Fixture

### ISSUE THREAD

**Issue by APerricone** [Birch-san/box2d-wasm#28]
Hi, in both classes are missing the restitution threshold, as we can see on documentation of box2D 2.4.1 https://box2d.org/documentation/structb2_fixture_def.html and https://box2d.org/documentation/classb2_fixture.html

**Comment by Birch-san** [comment]
I've now exposed restitutionThreshold in b2Fixture, b2FixtureDef and b2Contact:

https://github.com/Birch-san/box2d-wasm/commit/aed4fe0a772d9627c0262f78fff4841a0c1c0ffa  
https://github.com/Birch-san/box2d-wasm/commit/b8c98364a085a0dd1371707778c28576365bdb96

It's released in `box2d-wasm@4.0.2`.

I've also now published a separate npm package, `liquidfun-wasm@4.0.2`.

So, if you install `box2d-wasm@^4.0.2`: you should now stay on mainline releases.  
no further liquidfun releases will be published under the `box2d-wasm` package name.

**Comment by APerricone** [comment]
you are great, I'm glad you followed my suggestions, makes me feel important  😀 many thanks
