### ISSUE TITLE
'enabled' attribute is missing from b2BodyDef

### ISSUE THREAD

**Issue by dimitrisx** [Birch-san/box2d-wasm#38]
The `b2BodyDef` (in box2d-wasm/Box2D.idl) is missing the 'enabled' attribute.

**Comment by Birch-san** [comment]
agreed; thanks for raising.

will expose this and also attend to https://github.com/Birch-san/box2d-wasm/issues/36 next time I have the hood open.

in the meantime: I suppose you'll have to use `IsEnabled` / `SetEnabled()` on the body _after_ it's been created.

**Comment by Birch-san** [comment]
v7.0.0 exposes `b2BodyDef#enabled`
