### ISSUE TITLE
vue2.0 run wrong

### ISSUE THREAD

**Issue by a6965921** [Birch-san/box2d-wasm#42]
`Failed to compile.

./node_modules/box2d-wasm/dist/es/Box2D.simd.js
Module parse failed: Unexpected token (3:25)
You may need an appropriate loader to handle this file type.
| 
| var Box2D = (function() {
|   var _scriptDir = import.meta.url;
|   
|   return (
 @ ./node_modules/box2d-wasm/dist/es/entry.js 25:8-33
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/index.vue
 @ ./src/pages/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js`

**Comment by Birch-san** [comment]
from `3:25` it looks like it's referring to `import.meta.url`. this is an ES2020 feature.

the complaint comes from babel-loader.  
probably you need [`@babel/plugin-syntax-import-meta`](https://babeljs.io/docs/en/babel-plugin-syntax-import-meta), in order for babel to be able to parse the module.  
the idiomatic way to enable this plugin is by using the [`@babel/preset-env`](https://babeljs.io/docs/en/babel-preset-env) preset in your babel config.

the other thing you could do is avoid importing the ES module distribution of box2d-wasm, and import the UMD distribution (`box2d-wasm/dist/umd/entry.js`) instead.

**Comment by a6965921** [comment]
can you write vuecli demo   I always fail to compile
![Uploading image.png…]()

**Comment by a6965921** [comment]
![image](https://user-images.githubusercontent.com/1198840/168428879-5bc13920-3e6d-4ab9-8eb8-9926293bf4e3.png)

**Comment by Birch-san** [comment]
does it need to be Vue 2.0? I have box2d-wasm importing successfully in vue-cli 2.0 with Vite, but I don't know enough legacy Vue.js to make an asynchronous component; it's hard to find any documentation for obsolete versions.

**Comment by Birch-san** [comment]
looking at your screenshot, it looks like you are putting a _babel plugin_ into your _webpack plugins_.

`@babel/plugin-syntax-import-meta` should go into your _`.babelrc`_ (or wherever you specify your babel config).

**Comment by a6965921** [comment]
![image](https://user-images.githubusercontent.com/1198840/168458742-7cad21e3-62da-459c-b406-01bb25a59d51.png)
