### ISSUE TITLE
Module not found: Error: Can't resolve 'path' in 'D:\vuecli\hello-world\node_modules\box2d-wasm\dist\es'

### ISSUE THREAD

**Issue by a6965921** [Birch-san/box2d-wasm#46]
![image](https://user-images.githubusercontent.com/1198840/168460159-072f7906-2ef1-462f-91df-ab2d13d7ac96.png)

**Comment by Birch-san** [comment]
Yes, that's expected in webpack 5. You can fix it by following the advice in that error message.  
https://github.com/Birch-san/box2d-wasm/issues/26#issuecomment-814328442

**Comment by a6965921** [comment]
how to use webpack   Do not compile when referencing JS

**Comment by Birch-san** [comment]
I don't understand the question; what's the error message?

**Comment by a6965921** [comment]
can you user vue-cli(vue2.X)  write demo  Put it in GitHub  I need to refer to it

**Comment by liangchen-harold** [comment]
I've successfully ran with vue3, here is my vue.config.js

``` js
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true,
  // workaround for box2d-wasm
  configureWebpack: config => {
    Object.assign(config.resolve.fallback = { fs: false, path: false })
  }
})
```
