### ISSUE TITLE
GetUserData() can't get userdata 111

### ISSUE THREAD

**Issue by a6965921** [Birch-san/box2d-wasm#47]
`  var bd_ground = new b2BodyDef();
  bd_ground.set_userData(111);
  var ground = world.CreateBody(bd_ground);
  var shape = new b2EdgeShape();
  shape.SetTwoSided(new b2Vec2(0, 38), new b2Vec2(800 / pixelsPerMeter, 38));
  ground.CreateFixture(shape, 0);
  console.log(ground.GetUserData());`

**Comment by Birch-san** [comment]
https://github.com/Birch-san/box2d-wasm/blob/master/docs/user-data.md
