### ISSUE TITLE
How to move the rigid body position after the rigid body is created

### ISSUE THREAD

**Issue by a6965921** [Birch-san/box2d-wasm#49]
How to move the rigid body position after the rigid body is created

i can't find SetPositon

**Comment by Birch-san** [comment]
best way is to create a mouseJoint:  
https://github.com/Birch-san/liquidfun-play-2/blob/master/src/demo/gravity.ts#L182

that's how I attach the planet to the mouse:  
https://birchlabs.co.uk/liquidfun-wasm/

or you could use `SetTransform()`:  
https://stackoverflow.com/a/8582770/5257399
