### ISSUE TITLE
Difference with box2d.js

### ISSUE THREAD

**Issue by Cretezy** [Birch-san/box2d-wasm#5]
Hello, I think a comparison between this and https://github.com/kripken/box2d.js would be very useful.

**Comment by Birch-san** [comment]
The most important user-facing differences are:

| Criteria | [`box2d.js`](https://github.com/kripken/box2d.js) | [`box2d-wasm`](https://github.com/Birch-san/box2d-wasm) 
| --- | --- | --- |
| [Box2D](https://github.com/erincatto/box2d) version compatibility | v2.3.1 | v2.4.1 (latest) |
| TypeScript declarations | No | Yes |
| Distributes UMD module | Yes | Yes |
| Distributes ES module | No | Yes |
| Distributes WebAssembly | Yes | Yes |
| Distributes asm.js (for older browsers) | Yes | No |

There shouldn't be any particular size or performance differences (we both compile the same C++ files with moreorless the same flags).

There shouldn't be any particular differences in feature-set (we export Box2D functionality via moreorless the same WebIDL bindings; I merely updated the bindings to support v2.4.1)

As for _how it's developed_, the differences are:

- Different build system, to support the newer cmake build system introduced in Box2D v2.4.0.
- Different approach to version controlling source code and build output, for tidiness (see [project aims](https://github.com/Birch-san/box2d-wasm/blob/master/README.project-aims.md))

**Comment by Birch-san** [comment]
Closing on the basis that I've now added this detail to the README.
